---
title: "Various Weather Data around NY State"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include = FALSE}
library(flexdashboard)

Packages <- c("tidyverse", "viridis", "dplyr", "readxl", "plotly", "flexdashboard", "p8105.datasets")
invisible(lapply(Packages, library, character.only = TRUE))

data("ny_noaa")

base_df <- ny_noaa %>% 
  janitor::clean_names() %>% 
  drop_na() %>%                                                     # drop any NA in any column
  filter(id %in% c("USW00094728", "USC00300961", "USC00306164", "USC00307799", "USW00014735")) %>% 
  mutate(location = case_when(id == "USW00094728" ~ "Manhattan",
                              id == "USC00300961" ~ "Bronx",
                              id == "USC00306164" ~ "Ogdensburg",
                              id == "USC00307799" ~ "Slide Mountain",
                              id == "USW00014735" ~ "Albany"),
         tmin = as.numeric(tmin)/10,                                # convert from tenths to regular C
         tmax = as.numeric(tmax)/10,
         year = lubridate::year(date),                              # turn to specified date format
         month = lubridate::month(date),
         date = lubridate::day(date)) %>% 
  select(location, year, month, date, everything(), -id, -snwd)

```

Column {data-width=600}
-----------------------------------------------------------------------

### Annual Snowfall (mm) fluctuations

```{r}

base_df %>% 
  select(location, year, month, snow) %>%
  group_by(location, year) %>% 
  summarize(yearly_snow = sum(snow)) %>% 
  plot_ly(y = ~yearly_snow, x = ~year, type = "scatter", mode = "lines",     # make line graph
          color = ~location, colors = viridis_pal(option = "D")(5)) %>%      # tells viridis to get 5 colors 
  layout(
    xaxis = list(
      title = "Year",
      autotick = FALSE, tick0 = 1980, dtick = 2, tickangle = 45),            # manually assigns ticks/tick-gaps
    yaxis = list(
      title = "Annual Snowfall (mm)"
    ))

```

Column {data-width=400}
-----------------------------------------------------------------------

### Manhattan Monthly Temperature (C) in 2010

```{r}

base_df %>% 
  select(location, year, month, tmin, tmax) %>%
  filter(location == "Manhattan",
         year == 2010) %>%
  pivot_longer(tmax:tmin,
               names_to = "obs",
               values_to = "temp") %>% 
  plot_ly(y = ~temp, x = ~month, type = "scatter", mode = "markers",     
          color = ~obs, opacity = 0.8) %>%
  layout(
    xaxis = list(
      title = "Month",
      autotick = FALSE, tick0 = 1, dtick = 1),
    yaxis = list(
      title = "Temperature (C)"
    ))

```

### Bronx's Monthly Precipitation & Mean Min-Temp in 2010

```{r}

base_df %>% 
  select(location, year, month, prcp, tmin) %>%
  filter(location == "Bronx",
         year == 2010) %>% 
  group_by(month) %>% 
  summarize(total_prcp = sum(prcp),
            avg_tmin = mean(tmin)) %>% 
  plot_ly() %>% 
  add_trace(x = ~month, y = ~total_prcp, type = "bar", name = "Precip\n(mm)",  # add bar graph
            hoverinfo = "text",                                                      # add hoverinfo
            text = ~paste(total_prcp, " mm")) %>%                                    # hoverinfo content
  add_trace(x = ~month, y = ~avg_tmin, type = "scatter", mode = "line", name = "Min\nTemp (C)", # add line graph
            yaxis = "y2",                                                                      # specify 2nd y-axis
            hoverinfo = "text",
            text = ~paste(avg_tmin, " C")) %>% 
  layout(
    yaxis = list(
      side = 'left', 
      title = 'Precipitation (mm)', 
      showgrid = FALSE, zeroline = FALSE),
    yaxis2 = list(
      side = 'right', overlaying = "y", 
      title = 'Min Temp (C)', 
      showgrid = FALSE, zeroline = FALSE),
    xaxis = list(
      title = "Month",
      autotick = FALSE, tick0 = 1, dtick = 1, tickangle = 0)
  )

```

